version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Installing dependencies..."
      - cd $CODEBUILD_SRC_DIR
      - npm ci
      
  pre_build:
    commands:
      - echo "Running tests..."
      - npm test
      
  build:
    commands:
      - echo "Building..."
      - npm run build
      - npx cdk synth
      
  post_build:
    commands:
      - echo "Build completed successfully!"

artifacts:
  base-directory: cdk.out
  files:
    - '**/*'

cache:
  paths:
    - node_modules/**/* 